[package]
name = "downloader4etesty2"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = "0.7.5"
reqwest = { version = "0.12.20", features = [
    "rustls-tls", # simplifies package management on NixOS
    "blocking",
], default-features = false }
scraper = "0.23.1"
yaml-rust = "0.4.5"
